import { createContext } from "react";
import { PlayerStats } from "./PlayerStats";
import StoryFrame from "./StoryFrame";
import { TimeBucket } from "./TimeBuckets";

export var StoryDatabase = [
  new StoryFrame("Welcome to f!rosh week!", ["Okay!"], ['This is a text adventure about your first semester, made by Spark! The outcomes of previous choices will appear here, while your next opportunity will appear below.'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [[]], TimeBucket.FROSH_WEEK, true), //entry story
  new StoryFrame("You've gotten to the purple dye station. It's a tradition to remember those submarine engineers lost at sea.", ["No dye, thanks.", "Dye your arm.", "Dye your whole body."], ['You pass the station. Maybe another time?', 'Your arm drips with violet dye.', 'You convince someone to pour a bucket of dye over you. It tastes ... unpleasant, but you are now fully purple.'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [['SkuleSpirit', -1],['SkuleSpirit', +1],['SkuleSpirit', +5,'Health',-1]], TimeBucket.FROSH_WEEK),
  new StoryFrame("Your frosh group makes it to Nathan Phillips Square. Bystanders look on, some warily, some with anticipation.", ["Jump in!", "Push your friend!", "Stand and watch."], ['You jump in with the crowd. Several hundred engineers-to-be are already splashing each other.', 'They fall in, sputtering, then drag you in. Both of you are soaking by the time everyone leaves.', 'Watching from the edge of the pool, you dip your toes in. It\'s pretty cold, maybe you made the right choice.'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [['Social', +1],['Social',+1,'FriendExperiences',+1],['Social', -1]], TimeBucket.FROSH_WEEK),
  new StoryFrame("You walk back to campus, from downtown, then return to your residence with your frosh kit over your shoulder. The heat of the day has almost dissipated entirely, and you're looking forward to reorganizing your closet and chatting with roommates. Maybe you'll go out for dinner somewhere.", ["Chat with the other people in your group", 'Chat with your f!rosh leedur',"Admire the city"], ['You learn the names of some people in your discipline, and talk about how excited you are to start.', 'You learn some interesting things, courses to take, lectures to avoid, the best libraries ...', 'You notice a few shortcuts that might come in handy later. Queen St, W, St. Patrick, hm... you\'re getting the hang of this.'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [['Social',+1],['Social', +1, 'UpperYearWisdom', +1],['TorontoKnowledge', +2]], TimeBucket.FROSH_WEEK, false, true), //exit story

  new StoryFrame("The club fair is being held in Bahen this year. The first two floors are packed (within reason) with clubs and design teams looking to recruit new members.", ["Visit the Spark Design Club booth!", "Look at the other design clubs", "...is there a cabbage team?"], ['Spark is a club where you get hands on experience, and get to build something fun! We make electromechanical displays and games from scratch, designed and built fully by us (and you? ... Join our mailing list for more info (scroll down)).', 'You feel like some other clubs might be interesting to look at, but you\'re eventually drawn back towards the Spark Booth.', 'Yes, but Spark is _definitely_ more interesting than a cabbage club.'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [], TimeBucket.CLUB_FAIR, true),
  new StoryFrame("An old display stands to the left of the Spark Design Club booth. It's an assembly of flashing lights and whirring motors, with a small crowd taking turns to play.", ["Go up to the booth.", "Talk to the Spark leads."], ['You fiddle with the buttons, and you notice you\'re controlling a mechanized pong arcade machine. They tell you that the display took a few months to design, with a variety of students from all disciplines and years. "Join us at our next build day! It\'s where we build these displays all at once." they say, inviting you. (Join our mailing list (scroll down) to be notified!)', 'They tell you that the display took a few months to design, with a variety of students from all disciplines and years. "Join us at our next build day! It\'s where we build these displays all at once." they say, inviting you. (Join our mailing list (scroll down) to be notified!)'], [], 'https://images.unsplash.com/photo-1576485976138-6c3cff620ae8?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80', [['SparkVisited', +2], ['SparkVisited', +1]], TimeBucket.CLUB_FAIR, false, true),

  // autoprocessed
  new StoryFrame("You need to print a report for your Eng. Communication & Design class.", ["You go to one of the ECE computer labs in Sanford Fleming or GB", "You go to a library", "You don't print it"], ["You get to print your stuff for free and in colour or B/W (if you're in some of labs, check out ECF print quotas!)", "You have to pay a few cents to print, but maybe you've found a cool new study spot!", "You suffer :(((("], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic',2],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("There's a quiz this afternoon and you have a free hour at noon...", ["You decide to study and eat lunch in the Pit, the basement of Sanford Fleming, a popular engineering hangout.", "You skip eating lunch and go to the quiet study rooms in the library on the second floor of Sanford Fleming to study", "You go to Gerstein library and sneak in some food as you study"], ["You get to eat, study with your friends, and relax :) You do moderately well on the quiz.", "You are able to focus easily and ace the quiz but your empty stomach makes noises so loud everyone taking the quiz hears...", "You're a bit rushed and sweaty since Gerstein is further away, but you were able to study well."], [], '', [['Health', 1, 'Social', 2, 'Extracurricular', 0, 'Academic', 1],['Health', -2, 'Social', 0, 'Extracurricular', 0, 'Academic', 3],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("It's the first day of Fall Reading Break!", ["You write out a detailed schedule of what you want to do on each day", "You go out all day and night with some friends", "You write a general goals list of what you need to finish, in order of priority"], ["You are unable to finish everything on the list, but you make good progress. Things don't always work out and that's okay!", "You're massively hung over the next day.", "You finish all the high priority items and have time to see your friends sometimes."], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', -1, 'Social', 2, 'Extracurricular', 0, 'Academic', -1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.FALL_READING_WEEK),
  new StoryFrame("First day of Linear Algebra... where do you sit?", ["Near the front, in the middle of the row", "Aisle seat in the middle of the classroom", "Back of the class"], ["You feel a bit confused about the content, but the professor notices and tries to solve the source of your confusion.", "Someone sits next to you and they ask a question you also had. You get their contact info after class.", "You make a friend who sits by you but both of you spend most of the class on your phones..."], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 5],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 3],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Between classes on a Thursday afternoon, you notice students gathered around a tower of beer cans stacked high in the main floor of Myhal... it's Isengard!", ["I don't really have time for this, I have class", "Seems like fun, maybe I'll watch for a few minutes", "Contribute to the tower!"], ["You arrive early to your next class, getting great seats", "You stay for a bit, getting some pictures and chatting with a few new people before moving onto your next class.", "You miss your next class, but marvel at the structure you made with several new friends in different disciplines"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 2, 'Extracurricular', 1, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You pass this club booth for the Spark Design Club!!!!", ["You stop and chat with the wonderful and welcoming Spark Execs :)", "You smile and wave but keep walking", "You hang back but listen as an Exec explains the club to another person"], ["You get to learn about a cool club that created the game you're playing RIGHT NOW and you sign up for the mailing list (scroll down) so you can attend future events :) starting off the year right <3", "You feel... an emptiness.... of not learning about such a cool club... ", "You get to learn more about the club and eventually ask some questions of  your own :) kudos for reaching out"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 3, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', -2, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 2, 'Academic', 0]], TimeBucket.CLUB_FAIR),
  new StoryFrame("Tonight is Halloween, but tomorrow is something even more spooky... your Calculus midterm!", ["You hang out with some friends and study", "You go out to a Halloween party you heard from a friend of a friend", "You study by yourself in a library"], ["You pass around a bucket of candy in the study group and get to ask your friends a lot of questions to clarify. It wasn't the most productive time but you had a good time.", "You get so hungover the next day you almost vomit on the test paper. At least the party was fun.", "You study well and sleep early, and coincidentally see a friend in the library."], [], '', [['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', 1],['Health', -2, 'Social', 3, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 1, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.HALLOWEEN),
  new StoryFrame("It's a reaaally cold day but you have a 9AM class...", ["You bundle up and trundle out to face the elements on your way to class", "You get up and have breakfast, texting and checking if any of your friends are going today", "You go back to sleep"], ["You are one of the few people in class today and end up chatting with one of the lecturers. You actually understand everything that was taught today!", "You skip the first few classes and get notes from your friends. You spend the morning catching up on work and head out in the afternoon after it marginally warms up.", "You wake up at 3pm...."], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 1, 'Social', 0, 'Extracurricular',
  0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You're desperately lost in one of your classes and the midterm is in two weeks...", ["You go to office hours with your professor", "You go to your tutorial and stick around afterwards to ask more questions", "You ask all your friends questions about different concepts you're confused about"], ["You feel slightly intimidated and embarrassed about your confusion, but no one else comes to office hours so your professor spends the entire time explaining concepts to you and you feel more confident!", "You feel comfortable chatting with your TA and they offer their email for any more questions you have; which comes in handy over the weekend when you start doing more of the homework problems.", "You have a slightly patchwork understanding but are comforted by the fact that no one else seems to know what's going on either... "], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health',
  0, 'Social', 1, 'Extracurricular', 0, 'Academic', 1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("It's time to make GINGERBREAD BRIDGES at Godiva Week but you have class right now...", ["Watch from a table in the Pit but don't participate", "Join in with some people you haven't met before", "Go to class"], ["You get a bit bored just watching and end up slipping into the back of your class mid way through.", "Your bridge comes in second (right behind that of the Civ profs...) but the new friends you made are the real prize. You add them on Facebook and hope to stay in touch!", "You are very studious and get a tip on what might be on the next test!"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_READING_WEEK),
  new StoryFrame("You get a day off from classes for Thanksgiving!", ["You take a day to treat your self, call your family, and sleep more", "You take the time to study more because the grind never stops", "You go out during the day to hang out with friends and go drinking at night"], ["You feel refreshed and content, ready to tackle studying for the next midterm with confidence.", "You feel slightly burnt out on Saturday night...", "You have a good time but you're too hungover to function the next day."], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 3],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', -1, 'Social', 2, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.THANKSGIVING),
  new StoryFrame("You arrive at the front doors of myhal for your ESP tutorial. Your tutorial is on the third floor.", ["Run up the stairs", "Walk up the stairs", "Take the elevator"], ["Phew, what a great workout! You arrive five minutes early.", "You know you don\'t have time to wait for the elevator. You make your way up the stairs and arrive just as the tutorial is about to start. ", "After waiting a few minutes for the elevator to arrive, you notice the elevator is still on floor 8. You decide to take the stairs instead and arrive rather late."], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("While you're walking on front campus, a medical-masked ArtSci tries to steal your hard hat off your head!", ["Scream", "Run away", "Hold your hard hat with the underhanded power grip"], ["They grab your hard hat, then laugh and hand it back to you while introducing themselves. You just made a friend!", "You narrowly escape with your hard hat still on your head! Your friends laugh when you tell them what happened.", "The ArtSci realizes they\'ve been outsmarted and walks away defeated. Your Frosh leedur gives you a high-five."], [], '', [['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FROSH_WEEK),
  new StoryFrame("You notice your water bottle is nearly empty. There are a few minutes before class starts.", ["Go to Sanford Fleming", "Go to Myhal", "Go to Bahen"], ["After struggling with the knee-high water fountain, someone informs you there is a better water fountain in the Pit. You refill your bottle and head to class.", "After wandering around, you realize there are no water fountains on the first and second floor of Myhal. You head back to class, feeling a little parched.", "You quench your thirst at a water fountain near the Cube and head to class."], [], '', [['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You've been studying Calculus for several hours and it's getting quite late. Your eyelids start to droop.", ["Get some rest", "Stay up for a few hours", "Sleep is for the weak!"], ["You feel super refreshed and finish your studying with time left to spare at the end of the day. Time to relax!", "You notice your productivity declining and decide to go to bed. You wake up feeling tired but still able to pay attention in class the next day.", "The words start to blur on the page as your eyes slip shut. You wake up feeling groggy and have trouble paying attention in class the next day."], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Lunchtime! What to eat?", ["Find food at the Pit", "Find a food truck", "Skip lunch"], ["You find some buddies at a table and savor your meal from the Hard Hat Cafe and Veda. If you packed your own food, you're enjoying it now.", "You savor the food you bought from the nearby food truck.", "Later that day, your stomach rumbles, distracting you throughout the lecture. You regret skipping lunch."], [], '', [['Health', 1, 'Social', 1, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Your friends invite you to board game night tonight, but you have a lab tomorrow that you're not prepared for.", ["Grind out the prelab", "Hang out at games night", "Leave games night early to finish the prelab"], ["Staying on top of your studies is more important. You tell yourself you'll meet with your friends later.", "You treasure the time you have with your friends. The lab isn't worth that much, anyway.", "You have a great time with your friends and have enough time to finish the prelab. You wake up a little tired the next day and receive a good grade on your lab."], [], '', [['Health', 0, 'Social', -1, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', -2],['Health', -1, 'Social', 1, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Well, it looks like your time here is up! You've made it through most of your first semester in UofT Engineering, with exams looming on the horizon and winter break just a little past that. Congratulations!", ["Thanks for playing!"], ["Have a great rest of F!rosh week! Be sure to check out the Spark design club at the clubs fair, and join our mailing list (scroll down) to get updates about our Annual General Meeting, coming soon."], [], '', [['Health', 0, 'Social', -1, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', -2],['Health', -1, 'Social', 1, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.END),
]

export const InitStoryDatabase = () =>{
  //other obvious initialization 
  StoryDatabase = StoryDatabase.map((frame) => {
    return {...frame, read: false}
  })
  console.log("initialized story database")
  console.dir(StoryDatabase)
}

export const GetOutcomeByIndex = (currentFrame, choiceIndex) => {
  return currentFrame.storyOutcomes[choiceIndex]
}
