import { createContext } from "react";
import { PlayerStats } from "./PlayerStats";
import StoryFrame from "./StoryFrame";
import { TimeBucket } from "./TimeBuckets";

export var StoryDatabase = [
  new StoryFrame("Welcome to f!rosh week!", ["Okay!"], ['Made by Spark.'], [], 'https://picsum.photos/200/300', [], TimeBucket.FROSH_WEEK, true), //entry story
  new StoryFrame("You've gotten to the purple dye station. It's a tradition to remember those submarine engineers lost at sea.", ["No dye, thanks.", "Dye your arm.", "Dye your whole body."], ['You pass the station. Maybe another time?', 'Your arm drips with violet dye.', 'You convince someone to pour a bucket of dye over you. It tastes ... unpleasant, but you are now fully purple.'], [], 'https://picsum.photos/200/300', [['SkuleSpirit', -1],['SkuleSpirit', +1],['SkuleSpirit', +5,'Health',-1]], TimeBucket.FROSH_WEEK),
  new StoryFrame("Your frosh group makes it to Nathan Phillips Square. Bystanders look on, some warily, some with anticipation.", ["Jump in!", "Push your friend!", "Stand and watch."], ['You jump in with the crowd. Several hundred engineers-to-be are already splashing each other.', 'They fall in, sputtering, then drag you in. Both of you are soaking by the time everyone leaves.', 'Watching from the edge of the pool, you dip your toes in. It\'s pretty cold, maybe you made the right choice.'], [], 'https://picsum.photos/200/300', [['Social', +1],['Social',+1,'FriendExperiences',+1],['Social', -1]], TimeBucket.FROSH_WEEK),
  new StoryFrame("You walk back to campus, from downtown, then return to your residence with your frosh kit over your shoulder. The heat of the day has almost dissipated entirely, and you're looking forward to reorganizing your closet and chatting with roommates. Maybe you'll go out for dinner somewhere.", ["Chat with the other people in your group", 'Chat with your f!rosh leedur',"Admire the city"], ['You learn the names of some people in your discipline, and talk about how excited you are to start.', 'You learn some interesting things, courses to take, lectures to avoid, the best libraries ...', 'You notice a few shortcuts that might come in handy later. Queen St, W, St. Patrick, hm... you\'re getting the hang of this.'], [], 'https://picsum.photos/200/300', [['Social',+1],['Social', +1, 'UpperYearWisdom', +1],['TorontoKnowledge', +2]], TimeBucket.FROSH_WEEK, false, true), //exit story

  new StoryFrame("The club fair is being held in Bahen this year. The first two floors are floor are packed (within reason) with clubs and design teams looking to recruit new memebers.", ["Visit the Spark Design Club booth!", "Look at the other design clubs", "...is there a cabbage team?"], ['Promotional material', 'You feel like some other clubs might be interesting to look at, but you\'re eventually drawn back towards the Spark Booth.', 'Yes, but Spark is _definitely_ more interesting than a cabbage club.'], [], 'https://picsum.photos/200/300', [], TimeBucket.CLUB_FAIR, true),
  new StoryFrame("An old display stands to the left of the Spark Design Club booth. It's an assembly of flashing lights and whirring motors, with a small crowd taking turns to play.", ["Go up to the booth.", "Talk to the Spark leads."], ['You fiddle with the buttons, and you notice you\'re controlling a mechanized pong arcade machine. They tell you that the display took a few months to design, with a variety of students from all disciplines and years. "Join us at our next build day! It\'s where we build these displays all at once." they say, inviting you. (Join our mailing list to be notified!)', 'They tell you that the display took a few months to design, with a variety of students from all disciplines and years. "Join us at our next build day! It\'s where we build these displays all at once." they say, inviting you. (Join our mailing list to be notified!)'], [], 'https://picsum.photos/200/300', [['SparkVisited', +2], ['SparkVisited', +1]], TimeBucket.CLUB_FAIR, false, true),

  new StoryFrame("Thanksgiving placeholder", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.THANKSGIVING),

  new StoryFrame("Halloween's coming up! You could use a break from studying.", ["Still, you have a midterm soon. Go to the library.", "Head to a party!", "Watch a game at Varsity stadium."], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.HALLOWEEN, true),

  new StoryFrame("HALLOWEEN placeholder 1", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.HALLOWEEN),

  new StoryFrame("FALL_SEMESTER placeholder", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.FALL_SEMESTER),

  new StoryFrame("FALL_READING_WEEK placeholder", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.FALL_READING_WEEK),

  new StoryFrame("FALL_EXAMS placeholder -- NO MORE STORIES AFTER THIS SO FAR", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.FALL_EXAMS),

  new StoryFrame("WINTER_BREAK placeholder -- NO MORE STORIES AFTER THIS SO FAR", ["Choice 1", "Choice 2", "Choice 3"], ['Outcome 1', 'Outcome 2', 'Outcome 3'], [], 'https://picsum.photos/200/300', [], TimeBucket.WINTER_BREAK),

  // autoprocessed
  new StoryFrame("You need to print something", ["You go to one of the ECE computer labs in Sanford Fleming or GB", "You go to a library", "You don't print it"], ["You go to one of the ECE computer labs in Sanford Fleming or GB", "You go to a library", "You don't print it"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', -2]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("There's a quiz this afternoon and you have a free hour at noon", ["You decide to study and eat lunch in the Pit, the basement of Sanford Fleming, a popular engineering hangout.", "You skip eating lunch and go to the quiet study rooms in the library on the second floor of Sanford Fleming to study", "You go to Gerstein library and sneak in some food as you study"], ["You decide to study and eat lunch in the Pit, the basement of Sanford Fleming, a popular engineering hangout.", "You skip eating lunch and go to the quiet study rooms in the library on the second floor of Sanford Fleming to study", "You go to Gerstein library and sneak in some food as you study"], [], '', [['Health', 1, 'Social', 2, 'Extracurricular', 0, 'Academic', 1],['Health', -2, 'Social', 0, 'Extracurricular', 0, 'Academic', 3],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("It's the first day of Fall Reading Break", ["You write out a detailed schedule of what you want to do on each day", "You go out all day and night with some friends", "You write a general goals list of what you need to finish, in order of priority"], ["You write out a detailed schedule of what you want to do on each day", "You go out all day and night with some friends", "You write a general goals list of what you need to finish, in order of priority"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', -1, 'Social', 2, 'Extracurricular', 0, 'Academic', -1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.FALL_READING_WEEK),
  new StoryFrame("First day of Linear Algebra... where do you sit?", ["Near the front, in the middle of the row", "Aisle seat in the middle of the classroom", "Back of the class"], ["Near the front, in the middle of the row", "Aisle seat in the middle of the classroom", "Back of the class"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Between classes on a Thursday afternoon, you notice students gathered around a tower of beer cans stacked high in the main floor of Myhal... it's Isengard!", ["I don't really have time for this, I have class", "Seems like fun, maybe I'll watch for a few minutes", "Contribute to the tower!"], ["I don't really have time for this, I have class", "Seems like fun, maybe I'll watch for a few minutes", "Contribute to the tower!"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 2, 'Extracurricular', 1, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You pass this club booth for the Spark Design Club!!!!", ["You stop and chat with the wonderful and welcoming Spark Execs :)", "You smile and wave but keep walking", "You hang back but listen as an Exec explains the club to another person"], ["You stop and chat with the wonderful and welcoming Spark Execs :)", "You smile and wave but keep walking", "You hang back but listen as an Exec explains the club to another person"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 3, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', -2, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 2, 'Academic', 0]], TimeBucket.CLUB_FAIR),
  new StoryFrame("Tonight is Halloween, but tomorrow is something even more spooky... your Calculus midterm!", ["You hang out with some friends and study", "You go out to a Halloween party you heard from a friend of a friend", "You study by yourself in a library"], ["You hang out with some friends and study", "You go out to a Halloween party you heard from a friend of a friend", "You study by yourself in a library"], [], '', [['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', 1],['Health', -2, 'Social', 3, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 1, 'Extracurricular', 0, 'Academic', 2]], TimeBucket.HALLOWEEN),
  new StoryFrame("It's a reaaally cold day but you have a 9AM class", ["You bundle up and trundle out to face the elements on your way to class", "You get up and have breakfast, texting and checking if any of your friends are going today", "You go back to sleep"], ["You bundle up and trundle out to face the elements on your way to class", "You get up and have breakfast, texting and checking if any of your friends are going today", "You go back to sleep"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You're desperately lost in one of your classes and the midterm is in two weeks...", ["You go to office hours with your professor", "You go to your tutorial and stick around afterwards to ask more questions", "You ask all your friends questions about different concepts you're confused about"], ["You go to office hours with your professor", "You go to your tutorial and stick around afterwards to ask more questions", "You ask all your friends questions about different concepts you're confused about"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("It's time to make GINGERBREAD BRIDGES at Godiva Week but you have class right now", ["Watch from a table in the Pit but don't participate", "Join in with some people you haven't met before", "Go to class"], ["Watch from a table in the Pit but don't participate", "Join in with some people you haven't met before", "Go to class"], [], '', [['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_READING_WEEK),
  new StoryFrame("You get a day off from classes for Thanksgiving", ["You take a day to treat your self, call your family, and sleep more", "You take the time to study more because the grind never stops", "You go out during the day to hang out with friends and go drinking at night"], ["You take a day to treat your self, call your family, and sleep more", "You take the time to study more because the grind never stops", "You go out during the day to hang out with friends and go drinking at night"], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 2],['Health', -1, 'Social', 2, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.THANKSGIVING),
  new StoryFrame("You arrive at the front doors of myhal for your ESP tutorial. Your tutorial is on the third floor.", ["Run up the stairs", "Walk up the stairs", "Take the elevator"], ["Run up the stairs", "Walk up the stairs", "Take the elevator"], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', -1]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("While you're walking on front campus, a medical-masked ArtSci tries to steal your hard hat off your head!", ["Scream", "Run away", "Hold your hard hat with the underhanded power grip"], ["Scream", "Run away", "Hold your hard hat with the underhanded power grip"], [], '', [['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 1, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FROSH_WEEK),
  new StoryFrame("You notice your water bottle is nearly empty. There are a few minutes before class starts.", ["Go to Sanford Fleming", "Go to Myhal", "Go to Bahen"], ["Go to Sanford Fleming", "Go to Myhal", "Go to Bahen"], [], '', [['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("You've been studying Calculus for several hours and it's getting quite late. Your eyelids start to droop.", ["Get some rest", "Stay up for a few hours", "Sleep is for the weak!"], ["Get some rest", "Stay up for a few hours", "Sleep is for the weak!"], [], '', [['Health', 2, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', 0, 'Social', 0, 'Extracurricular', 0, 'Academic', 1],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Lunchtime! What to eat?", ["Find food at the Pit", "Find a food truck", "Skip lunch"], ["Find food at the Pit", "Find a food truck", "Skip lunch"], [], '', [['Health', 1, 'Social', 1, 'Extracurricular', 0, 'Academic', 0],['Health', 1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0],['Health', -1, 'Social', 0, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),
  new StoryFrame("Your friends invite you to board game night tonight, but you have a lab tomorrow that you're not prepared for.", ["Grind out the prelab", "Hang out at games night", "Leave games night early to finish the prelab"], ["Grind out the prelab", "Hang out at games night", "Leave games night early to finish the prelab"], [], '', [['Health', 0, 'Social', -1, 'Extracurricular', 0, 'Academic', 2],['Health', 0, 'Social', 2, 'Extracurricular', 0, 'Academic', -2],['Health', -1, 'Social', 1, 'Extracurricular', 0, 'Academic', 0]], TimeBucket.FALL_SEMESTER),

]

export const InitStoryDatabase = () =>{
  //other obvious initialization 
  StoryDatabase = StoryDatabase.map((frame) => {
    return {...frame, read: false}
  })
  console.log("initialized story database")
  console.dir(StoryDatabase)
}

export const GetOutcomeByIndex = (currentFrame, choiceIndex) => {
  return currentFrame.storyOutcomes[choiceIndex]
}
